# Generated by Django 5.2.15 on 2026-07-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image_url',
            field=models.URLField(blank=True, help_text='Direct link to premium food image', max_length=500),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_spicy',
            field=models.BooleanField(default=False),
        ),
    ]
