# Generated by Django 5.2.15 on 2026-07-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0002_menuitem_image_url_menuitem_is_spicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('PREPARING', 'Preparing'), ('READY', 'Ready to Serve'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='RECEIVED', max_length=15),
        ),
    ]
